server:
  port: 8082

dubbo:
  application:
    name: springboot-dubbo-zk-user-srvice-provider
  registry:
    address: 192.168.47.133:2181,192.168.47.133:2182,192.168.47.133:2183
    protocol: zookeeper
