server:
  port: 8081
  servlet:
    context-path: /user-service-comsumer


dubbo:
  application:
    name: springboot-dubbo-zk-user-srvice-provider
  registry:
    address: zookeeper://95.168.3.224
  protocol:
    name: dubbo
    port: 20880